### PR TITLE
convert ctools plugin to info hook

### PR DESCRIPTION
**Pull request by herbdool**
Addresses #3

### CODE REVIEW

**Comment by herbdool** [comment]
@Graham-72 for review. I was curious how to do this conversion and I think I've got it working. Though I'm not entirely sure what this module does so please take a look.

**Comment by Graham-72** [comment]
@herbdool thank you very much for doing this. I hope to do a test within the next few days. I had forgotten all about this module which I quickly ported some time ago to meet a specific need but I don't think I have it in a production site now. What I needed it for was to rearrange the description and help text on a custom form so that where appropriate the explanation came above the field rather than below. In some situations this can improve the UI.

**Comment by bradbulger** [comment]
I'm trying this out now and it seems to work fine.

**Comment by Graham-72** [comment]
I have merged this so that it is included in any further testing of this port.

**Pull request merged**
